#!/usr/bin/env bash
# index_sessions.sh — build a human-readable index of every archived
# session, so sessions that share one flat projects/ dir (shared mode)
# or one instance dir can be teased apart and attributed to a project.
#
# There is NO recorded project<->session mapping: in shared mode all
# instances write to one projects/ dir, and the in-container cwd is
# always /workspace regardless of which host project was mounted. So this
# indexes the signals that DO survive in each transcript:
#   - date        first timestamp in the transcript
#   - title       Claude Code's auto-generated customTitle, if any
#   - prompt      first real user prompt (title-gen prompts skipped)
#   - hints       git remotes + distinctive /workspace/<sub> paths seen
#
# Output: INDEX.md in this dir, grouped by source, sorted by date.
# Read it to bucket sessions by project; nothing is moved or guessed.
#
# ponytail: jq per file, plain markdown out. No classifier — attribution
# is a human read, not a heuristic that would guess wrong silently.
set -euo pipefail

ARCHIVE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="$ARCHIVE_DIR/INDEX.md"

command -v jq >/dev/null || { echo "index: jq required" >&2; exit 1; }

{
    echo "# Session index"
    echo
    echo "One row per archived session. Generated by \`index_sessions.sh\`."
    echo "Attribution is by eye: match **title** / **prompt** / **hints** to a project."
    echo
} > "$OUT"

index_source() {
    local label="$1" projdir="$2"
    [ -d "$projdir" ] || return 0
    local files
    files=$(find "$projdir" -name '*.jsonl' 2>/dev/null)
    [ -n "$files" ] || return 0

    {
        echo "## $label"
        echo
        echo "| date | title | first prompt | hints |"
        echo "|---|---|---|---|"
    } >> "$OUT"

    # Emit one row per file, tab-joined, then sort by date column.
    while IFS= read -r f; do
        [ -n "$f" ] || continue

        # || true on every pipeline: grep exits 1 on no-match, which
        # would trip set -e inside command substitution and abort the run.
        local date title prompt hints
        date=$(jq -rs 'map(.timestamp // empty) | sort | .[0] // ""' "$f" 2>/dev/null | cut -c1-10 || true)

        title=$(jq -r 'select(.type=="custom-title") | .customTitle // empty' "$f" 2>/dev/null | head -1 || true)

        prompt=$( { jq -r 'select(.type=="user") | (.message.content? // .content? // empty)
                        | if type=="array" then (map(.text? // empty) | join(" ")) else . end' "$f" 2>/dev/null \
                 | grep -avE '^Summarize this task|^Reply with only|^<' \
                 | tr '\n' ' ' | head -c 120; } || true)

        # git remotes + /workspace/<subdir> mentions, deduped, comma-joined.
        hints=$( { grep -aoE '(github\.com[:/][A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+|/workspace/[A-Za-z0-9_.-]+)' "$f" 2>/dev/null \
                | grep -avE '/workspace/(memory|slides)$' \
                | sort -u | tr '\n' ',' | sed 's/,$//' | head -c 120; } || true)

        # Markdown-escape pipes in free text so the table doesn't break.
        title=${title//|/\\|}; prompt=${prompt//|/\\|}; hints=${hints//|/\\|}
        printf '%s\t| %s | %s | %s | %s |\n' \
            "${date:-0000-00-00}" "${date:-?}" "${title:-—}" "${prompt:-—}" "${hints:-—}"
    done <<< "$files" | sort | cut -f2- >> "$OUT"

    echo >> "$OUT"
}

for d in "$ARCHIVE_DIR"/*/; do
    label=$(basename "$d")
    index_source "$label" "$d/projects"
done

n=$(grep -cE '^\| [0-9?]' "$OUT" 2>/dev/null || echo 0)
echo "Indexed sessions -> ${OUT#$ARCHIVE_DIR/}  (${n} rows)"
